-- =============================================
-- NEXUO DATABASE SETUP - RUN IN SUPABASE SQL EDITOR
-- =============================================

-- DROP existing tables
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS products;

-- =============================================
-- PRODUCTS TABLE
-- =============================================
CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    price TEXT NOT NULL DEFAULT '0',
    category TEXT DEFAULT 'Indicator',
    description TEXT DEFAULT '',
    features TEXT DEFAULT '',
    download_link TEXT DEFAULT '#',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =============================================
-- ORDERS TABLE
-- =============================================
CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id TEXT NOT NULL UNIQUE,
    product_name TEXT NOT NULL,
    price TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT DEFAULT '',
    proof TEXT,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =============================================
-- INSERT SAMPLE PRODUCTS
-- =============================================
INSERT INTO products (name, price, category, description, features, download_link) VALUES
('NEXUO Neural Core', '249000', 'Python AI', 'Robot AI ini belajar dari pola pasar 5 tahun terakhir. Cocok untuk pemula yang takut ketinggalan momentum.', 'Auto Stop Loss,Panduan Lengkap,AI Learning', '#'),
('Trend Surfer EA', '199000', 'MQL5', 'Expert Advisor untuk menunggu tren besar terbentuk. Dilengkapi Trailing Stop agar profit tidak berbalik.', 'Follow Trend,Filter News,Low Drawdown', '#'),
('Smart Money Indicator', '129000', 'Pine Script', 'Indikator premium yang menandai area Bank Besar (Institutional) masuk pasar.', 'Deteksi Order Block,Alert ke HP,Video Tutorial', '#');

-- =============================================
-- ENABLE RLS (Optional - untuk production)
-- =============================================
-- ALTER TABLE products ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

-- =============================================
-- CREATE ANON POLICY (biar bisa read dari frontend)
-- =============================================
CREATE POLICY "Enable read access for all users" ON products FOR SELECT USING (true);
CREATE POLICY "Enable read access for all users" ON orders FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated users" ON orders FOR INSERT WITH CHECK (true);

-- =============================================
-- DONE!
-- =============================================